title: Risk Assessment Documentation
description: Documentation for risk assessment tools and matrices
baseurl: "/sqe" # the subpath of your site (repository name)
url: "https://jaewoojoung.github.io" # your GitHub Pages URL without the repository name
# Build settings
markdown: kramdown
plugins:
  - jekyll-relative-links
  - jekyll-last-modified-at
  - jekyll-data

# File handling
include:
  - "*.html"
  - "*.htm"

# Default front matter for HTML files
defaults:
  -
    scope:
      path: ""
    values:
      last_modified_at: site.time
